call init#AddPlugin( ['多光标支持', 'mg979/vim-visual-multi',  'visual-cursor.vim'])
call init#AddPlugin( ['状态栏', 'nvim-lualine/lualine.nvim', 'lualine.vim'])
call init#AddPlugin( ['增加、修改包围的括号或者tag', 'tpope/vim-surround' ])
call init#AddPlugin( ['treesitter语法高亮', 'nvim-treesitter/nvim-treesitter', 'treesitter.vim', ['heavy'], "{'do':':TSUpdate'}"])
call init#AddPlugin( ['treesitter对象', 'nvim-treesitter/nvim-treesitter-textobjects', 'treesitter-textobjects.vim', ['heavy']])
call init#AddPlugin( ['快速跳转', 'folke/flash.nvim', 'flash.vim', ['heavy']])
call init#AddPlugin( ['git状态', 'lewis6991/gitsigns.nvim', 'gitsigns.vim'])
call init#AddPlugin( ['mini功能合集', 'echasnovski/mini.nvim','mini.vim'])
call init#AddPlugin( ['图标', 'kyazdani42/nvim-web-devicons'])
call init#AddPlugin( ['自动保存', 'Pocco81/auto-save.nvim', 'auto-save.vim'])
call init#AddPlugin( ['ClaudeCode', 'coder/claudecode.nvim', 'claudecode.vim'])
call init#AddPlugin( ['QOL插件集', 'folke/snacks.nvim', 'snacks.vim'])
call init#AddPlugin( ['注释', 'preservim/nerdcommenter', 'nerdcommenter.vim'])
call init#AddPlugin( ['coc', 'neoclide/coc.nvim', 'coc.vim', [], "{'branch': 'release'}"])
call init#AddPlugin( ['lua函数集', 'nvim-lua/plenary.nvim'])
call init#AddPlugin( ['搜索', 'nvim-telescope/telescope.nvim', 'telescope.vim'])
call init#AddPlugin( ['会话自动保存', 'rmagatti/auto-session', 'auto-session.vim'])
call init#AddPlugin( ['浮动终端', 'akinsho/toggleterm.nvim', 'toggleterm.vim'])
call init#AddPlugin( ['diff工具', 'sindrets/diffview.nvim', 'diffview.vim', ['heavy']])
call init#AddPlugin( ['主题', 'dracula/vim'])
call init#AddPlugin( ['', '', 'custom.vim', ['vscode']])
call init#AddPlugin( ['', '', 'keybinding.vim', ['vscode']])
call init#AddPlugin( ['', '', 'colorscheme.vim' ])
